ALTER TABLE fraud_reports ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id);
ALTER TABLE saved_csv_data ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id);
ALTER TABLE saved_entity_data ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id);
